"""empty message

Revision ID: 8c590e917d22
Revises: 5c2bbc1ea455
Create Date: 2020-07-16 20:25:44.406831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c590e917d22'
down_revision = '5c2bbc1ea455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('dianzan_totle', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'dianzan_totle')
    # ### end Alembic commands ###
